name: Combine Lint, Test and Build into one job
on: push
jobs:
    combine-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: Install dependencies
              run: npm ci
            - name: Run Lint, Test and Build
              run: |
                  npm run lint
                  npm run test
                  npm run build
